### ISSUE TITLE
Support for partial play?

### ISSUE THREAD

**Issue by tombewley** [philihp/openskill.js#179]
Hi there! Documentation for TrueSkill implementations describe (rather vaguely) how it can handle "partial play", when a player is only present for a certain proportion of the game, so their contribution is down-weighted. This kind of weighting is a central part of the project I'm working on at the moment. Is partial play weighting also possible within the OpenSkill framework, and if so is it implemented somewhere in this library?

**Comment by philihp** [comment]
Partial play wasn't discussed in the original paper, however it is certainly I'd like to add to Openskill. I'd really want some more datasets of benchmark data in order to validate that it was done in a way that it still predicts outcomes well. There's a lot of data out there with full play, but I haven't found any real-world datasets of partial play among team/multiplayer matches.

Would you be able to provide a dataset of matches for your use case?

Alternatively, if you'd like to take a stab at implementing it yourself, a good place to start would be modifying [this function](https://github.com/philihp/openskill.js/blob/main/src/util.js#L31-L44)

The way TrueSkill handles this is by weighting each player. The Python implementation implements this interface [like this](https://trueskill.org/#partial-play). It's pretty subjective to the game/use case how you might weigh partial play, i.e. do you weigh players by how long they participated? Perhaps how many points they scored?

**Comment by philihp** [comment]
Closing this from inactivity, but feel free to reopen.
