### ISSUE TITLE
[Question] Python Port

### ISSUE THREAD

**Issue by daegontaven** [philihp/openskill.js#193]
I'm writing a python port of this package and I don't understand why this function results in 102.42 https://github.com/philihp/openskill.js/blob/8303d5994db93c0957c60194c344d13a9555c76b/src/__tests__/util/util-sum-q.test.js#L27

What exactly is this function supposed to return for 5 v 5?
```js
[204.84378810598616, 204.84378810598616]
```
or
```js
[204.84378810598616, 102.42189405299308]
```

If it's the latter, why and what does this function do?

**Comment by philihp** [comment]
That's wonderful! I'd love to link to you in the Readme when you're ready to publish it!

Regarding this function, sumQ, see Algorithm 4, step 3: https://www.csie.ntu.edu.tw/~cjlin/papers/online_ranking/online_journal.pdf

The latter, `[204.8..., 102.4...]` _should_ be correct, because the first team is before the second team. It might seem an awkward way of doing it at first, but the same general function also works for 3 or more teams.

That said, if you check https://www.csie.ntu.edu.tw/~cjlin/papers/online_ranking/, there's a zip file of C code. I generated a lot of my test case output from this, and the outputs should match pretty close, although there may be slight ill-conditioned results because of differences in how every language approximates some functions (for example Math.exp).

**Comment by daegontaven** [comment]
Thank you. You were right after all. My ranking function had an error that propagated to all util functions.

**Comment by philihp** [comment]
![image](https://user-images.githubusercontent.com/1247668/131575299-0e7365fc-d52c-4ed6-857b-3c78820e3f6f.gif)

**Comment by daegontaven** [comment]
Why is `iGamma` being multiplied here when the original paper's code doesn't do it?
https://github.com/philihp/openskill.js/blob/8303d5994db93c0957c60194c344d13a9555c76b/src/models/thurston-mosteller-part.js#L24

Original Paper's Code:
```c
Delta += sigsq_to_ciq/ciq*Wt(tmp, epsilon/ciq);
```

I'm assuming this is a feature you added yourself?

**Comment by daegontaven** [comment]
I'm assuming it was intended and published my package: https://github.com/OpenDebates/openskill.py

**Comment by philihp** [comment]
Oh yes! That was actually unintended on my part, and it's unclear if it's intentionally left out in the reference paper.

At 6.2, it omits TM-partial, but it's unclear why:
> γq in (50) is set as σi/ciq for BT-full. The same γq is applied to BT-partial and TM-full. For PL, we use γq = σi/c. The use of γq is further discussed later in this section

On line 286, in the description of TM-full in the paper for step 3.1.1, they say TM is the same as BT with the given difference, and in that they do not mention γ in the update of ηq at all... which if we were to go by that, we should have omitted γ from TM-full as well, which seems wrong.

FWIW, γ "feels" to me like it was added after the fact, so different use cases can tune how fast/slow sigma converges to zero. I guess we could have the default it to 1 for TM-partial, if we wanted to be true to the gospel, but I think it's more intuitive to have the same default gamma for all models. What do you think?

**Comment by daegontaven** [comment]
> FWIW, γ "feels" to me like it was added after the fact, so different use cases can tune how fast/slow sigma converges to zero.

I agree with you. It makes no sense why it's not included in TM-partial in the code. So perhaps it was an oversight? Either ways if it causes problems, it's better that gamma is configurable (as it already is).
