### ISSUE TITLE
Partial Play

### ISSUE THREAD

**Issue by umb-hub** [philihp/openskill.js#272]
Very nice work, I was reading documentation and I noticed that there is not any support to abandoned and partial games (Partial Play).

Is it possible to implement some kind of partial play's support (like in this [trueskill](https://github.com/sublee/trueskill/commit/414a2d783707cc8892aa68f7a72dc67810f982ac) implementation) or openskill's math is incompatible with this support?

Thanks you!

**Comment by philihp** [comment]
We could add it, and there are a number of ways it could be implemented. The first step would be to get a sufficiently large dataset of games with this data; otherwise I will be resistant to adding this unless we can empirically show that any of those ways can objectively improve the predictive capability of the library.

**Comment by philihp** [comment]
Hello! Just to close the loop on that - i'm about to release version 3.0.0. It allows for a more modular way of sending in models, and will let me/you/us experiment more with swapping out new models without needing to be imported directly, so you can experiment with partial play and other new factors that might be sent in.
