### ISSUE TITLE
Go Port

### ISSUE THREAD

**Issue by eullerpereira94** [philihp/openskill.js#376]
I'm working on a Go port, and I already have implemented the Plackett-Luce model. If it is not asking much, when I finish porting it, could you link it like the other ports?

**Comment by daegontaven** [comment]
This is awesome. As the author of the Python port I'd be willing to link your repository. Also if you can find time to implement https://github.com/philihp/openskill.js/issues/347 into the Go port, that would even more amazing.

**Comment by eullerpereira94** [comment]
I will add as an issue in my repo.

**Comment by philihp** [comment]
Of course! :)

**Comment by eullerpereira94** [comment]
Go port has all the three models, plus the capability of predicting wins and ties. Still working into that rank prediction. Need to implement a lot of tests. Then v1.0.0 will be ready. Closing because the "porting" is done. Don't feel comfortable with my port being linked yet, since the tests for Thurstone-Mosteller keeps failing. Even though the first six decimal places match, after that it deviates.

**Comment by philihp** [comment]
No worries! Feel free to open a PR whenever you're ready.

With Thurstone-Mosteller, deep under the hood, different languages and packages will sometimes implement the gaussian/normal distribution functions differently _because reasons_. My implementation is ultimately using [this](https://github.com/errcw/gaussian/blob/master/lib/gaussian.js#L7-L14), and I am guessing you might be using [this](https://go.dev/src/math/erf.go). Over time that difference might compound and make someone's rating 42.00123 rather than 42.00172.

**Comment by philihp** [comment]
No worries! Feel free to open a PR whenever you're ready.

With Thurstone-Mosteller, deep under the hood, different languages and packages will sometimes implement the gaussian/normal distribution functions differently because reasons. My implementation is ultimately using [this](https://github.com/errcw/gaussian/blob/master/lib/gaussian.js#L7-L14), and I am guessing you might be using [this](https://go.dev/src/math/erf.go). Over time that difference might compound and make someone's rating 42.00123 rather than 42.00172, but that's okay with me if it's okay with you!

**Comment by eullerpereira94** [comment]
I'm cool with that. Sending a PR with v1.0.0
