### ISSUE TITLE
Starting values for MU and Sigma

### ISSUE THREAD

**Issue by hampusboas** [philihp/openskill.js#405]
Hi,

First of all, a big thank you for this awesome repository.

I've recently tried to implement this into my ladders for my gaming app.
But i have a problem finding the sweet spot for the default mu and sigma value for new participants.

I want all new users to start with an ordinal of 1000 and present it like an ELO for the rating of the users.

My problem: After the first round is completed the one who finished last gets way to much "negative" ranking and vice verse the one who wins gets way to high ranking and it would take multiple rounds to catch up for the looser.

So if i switch the results in round 2 the looser wins and the winner loose. The points for winning is like one third of the previous points lost. 

FYI, the ladder is about 30 rounds and in each rounds its 15 users.

I understand that the result will initially fluctuate until the sigma value has stabilized. But shouldn't it fluctuate both ways?

I'm using the default model and my currently starting values are { mu: 1500, sigma:167 }.
I've tried different models but with no success.

Thanks in advance and have a nice day!

**Comment by daegontaven** [comment]
Is there a reason you're using `167` for `sigma`? That's what is probably it's causing this issue. Generally you want `sigma` to follow the empirical rule for where 99.7% of the players fall into 3 standard deviations. If your `sigma` is too low, the system will have more confidence in the players skill.

Here is a graph showing the distribution where `sigma = mu/3` vs your distribution.
![image](https://user-images.githubusercontent.com/8206808/230382007-10179e01-a56f-4f34-baf6-5f17fa566cab.png)

As you can see, your distribution indicates the system is very confident in every new players ability. In reality when a new player starts out the system actually has no idea what the players skill is. So it's better for `sigma` or the standard deviation to allow for the possibility that a player could be be anywhere in the range of data with 99.7% certainty.

If you want to get exactly `1000` to display in leader boards and such, simply use the default `mu` and `sigma`. Then you can use this formula to get the result you want.

$$
\text{rating}  = \alpha * (((\mu \pm \delta) - 3 * \frac{\mu}{3}) + \psi)
$$

Here $\alpha$ is the scaling factor, $\delta$ is the shift from the mean and $\psi$ is a constant that is added so that scaling works.

Given $\mu = 25$, $\delta = 0$ (ie, we are not shifting the mean), $\psi=25= \mu$ and $\alpha = 40$:

$$
\text{rating} = 40 * (((25 + 0) - 3 * \frac{25}{3}) + 25) = 1000
$$

When $\mu \pm \delta = 25 + \frac{25}{3}$ and $\sigma = \frac{25}{3}$:

$$
\text{rating} = 40 * (((25 + \frac{25}{3}) - 3 * \frac{25}{3}) + 25) = 1333 + \frac{1}{3}
$$

Similarly, when $\mu \pm \delta = 25 - \frac{25}{3}$ and $\sigma = \frac{25}{3}$:

$$
\text{rating} = 40 * (((25 - \frac{25}{3}) - 3 * \frac{25}{3}) + 25) = 666 + \frac{1}{2} + \frac{1}{6}
$$

You can simply take the `mu` and `sigma` values from the `rating` object and simply plug them into this formula to simulate Elo.

In code it will look something like this:

```javascript
> const a1 = rating()
{ mu: 25, sigma: 8.333333333333334 }
> 40 * ((a1['mu'] - 3 * a1['sigma']) + 25)
1000
> const a2 = rating({ mu: 32.444, sigma: 5.123 })
{ mu: 32.444, sigma: 5.123 }
> 40 * ((a2['mu'] - 3 * a2['sigma']) + 25)
1683
```

**Comment by hampusboas** [comment]
Wow! Thank you for your detailed answer. This turned out so much better =) 

The reason I set sigma to 167 was because after my simulations, my result was as close as I expected. It is difficult when the ladder is so short to get a fair assessment and the sport of pro fishing practiced in the app there is a lot of randomness in who wins.

Again, many thanks for your time and detailed response.

Have a nice evening.
